name: broadcaadvendor
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.4.0
  get_it: ^7.6.4

  google_fonts: ^6.1.0

  build_runner: ^2.4.7
  bloc: ^8.1.2
  logger: ^2.0.2+1

  data_connection_checker_tv: ^0.3.5-nullsafety
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  local_auth: ^2.1.8
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  intl: ^0.19.0
  file_picker: ^6.2.0
  flutter_native_splash: ^2.4.0

  country_picker: ^2.0.25
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # flutter_native_splash: ^2.3.10
flutter_native_splash:
  color: "#030E4F"
  image: assets/images/splash_image.png
flutter:
  uses-material-design: true

  assets:
    - assets/images/
